-- DOWN: 001_initial_schema.down.sql
DROP TABLE IF EXISTS usage_events CASCADE;
DROP TABLE IF EXISTS invoices CASCADE;
DROP TABLE IF EXISTS endpoints CASCADE;
DROP TABLE IF EXISTS models CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS ledger CASCADE;
DROP TABLE IF EXISTS balances CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;
